name = "route-subdomain-to-path"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

[vars]
ROUTES = '''
{
  "/tone-curve": "https://tone-curve.underconstruction.fun",
  "/claude-chat-viewer": "https://claude-chat-viewer.tools.osteele.com",
  "/dialog-explorer": "https://dialog-explorer.underconstruction.fun",
  "/shutterspeak": "https://shutterspeak.underconstruction.fun",
  "/": "302:https://osteele.com/tools"
}
'''

[build]
command = "bun run build"

[dev]
port = 8787
