name = "route-subdomain-to-path"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

[vars]
ROUTES = '''
{
  "/tone-curve/*": "proxy:https://tone-curve.underconstruction.fun/*",
  "/claude-chat-viewer/*": "proxy:https://claude-chat-viewer.tools.osteele.com/*",
  "/dialog-explorer/*": "proxy:https://dialog-explorer.underconstruction.fun/*",
  "/kana-falls/*": "proxy:https://kana-game.underconstruction.fun/*",
  "/shutterspeak/*": "proxy:https://shutterspeak.underconstruction.fun/*",
  "/travel-photo-explainer/*": "proxy:https://travel-journal.tools.osteele.com/*",
  "/": "https://osteele.com/tools"
}
'''
# Enable image caching for specific routes
# Can be an array of route paths or boolean for all routes
CACHE_IMAGES = '["/claude-chat-viewer/*"]'

[build]
command = "bun run build"

[dev]
port = 8787
