name = "route-subdomain-to-path"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

routes = [ { pattern = "tools.osteele.com", custom_domain = true } ]

[build]
command = "bun run build"

[dev]
port = 8787
